const Module=require('module');
const originalLoad=Module._load;
let appRef=null,dbRef=null,registered=false;
const secret=process.env.JWT_SECRET||'change-this-secret-in-production';
const crypto=require('crypto');
const jwt=require('jsonwebtoken');
const now=()=>Date.now();
function register(){
 if(registered||!appRef||!dbRef)return; registered=true;
 const db=dbRef,app=appRef;
 db.exec(`CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,content TEXT DEFAULT '',actor_id INTEGER,reference_id TEXT,is_read INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS followers (follower_id INTEGER NOT NULL,following_id INTEGER NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(follower_id,following_id));
CREATE TABLE IF NOT EXISTS stories (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,media_url TEXT,content TEXT DEFAULT '',created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS story_views (story_id INTEGER NOT NULL,user_id INTEGER NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(story_id,user_id));
CREATE TABLE IF NOT EXISTS saved_posts (post_id INTEGER NOT NULL,user_id INTEGER NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS reports (id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_id INTEGER NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL);`);
 const auth=(req,res,next)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=jwt.verify(t,secret);const row=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);if(!row)return res.status(401).json({error:'Authentification requise'});req.user=u;req.dbUser=row;next()}catch{return res.status(401).json({error:'Authentification requise'})}};
 const notify=(uid,type,title,content='',actor=null,ref=null)=>{const r=db.prepare('INSERT INTO notifications(user_id,type,title,content,actor_id,reference_id,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,type,title,content,actor,ref==null?null:String(ref),now());return db.prepare('SELECT * FROM notifications WHERE id=?').get(r.lastInsertRowid)};
 app.get('/api/notifications',auth,(req,res)=>{const rows=db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100').all(req.user.id);res.json({notifications:rows,unread:rows.filter(x=>!x.is_read).length})});
 app.post('/api/notifications/read-all',auth,(req,res)=>{db.prepare('UPDATE notifications SET is_read=1 WHERE user_id=?').run(req.user.id);res.json({ok:true})});
 app.post('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})});
 app.get('/api/search',auth,(req,res)=>{const q=String(req.query.q||'').trim();if(!q)return res.json({users:[],posts:[],hashtags:[]});const users=db.prepare('SELECT id,username,display_name,avatar_url,bio,role FROM users WHERE username LIKE ? OR display_name LIKE ? ORDER BY display_name LIMIT 30').all('%'+q+'%','%'+q+'%');const posts=db.prepare('SELECT p.*,u.username,u.display_name,u.avatar_url FROM posts p JOIN users u ON u.id=p.author_id WHERE p.content LIKE ? ORDER BY p.id DESC LIMIT 30').all('%'+q+'%');res.json({users,posts,hashtags:q.startsWith('#')?[q.slice(1)]:[]})});
 app.get('/api/profile/:username',auth,(req,res)=>{const u=db.prepare('SELECT id,username,display_name,avatar_url,bio,created_at,role FROM users WHERE username=?').get(req.params.username);if(!u)return res.status(404).json({error:'Profil introuvable'});const followers=db.prepare('SELECT COUNT(*) c FROM followers WHERE following_id=?').get(u.id).c,following=db.prepare('SELECT COUNT(*) c FROM followers WHERE follower_id=?').get(u.id).c;const followingMe=!!db.prepare('SELECT 1 FROM followers WHERE follower_id=? AND following_id=?').get(req.user.id,u.id);const posts=db.prepare('SELECT p.*,u.username,u.display_name,u.avatar_url FROM posts p JOIN users u ON u.id=p.author_id WHERE p.author_id=? ORDER BY p.id DESC LIMIT 100').all(u.id);res.json({user:u,followers,following,followingMe,posts})});
 app.post('/api/users/:id/follow',auth,(req,res)=>{const id=Number(req.params.id);if(id===req.user.id)return res.status(400).json({error:'Action invalide'});const target=db.prepare('SELECT id,display_name,username FROM users WHERE id=?').get(id);if(!target)return res.status(404).json({error:'Utilisateur introuvable'});const ex=db.prepare('SELECT 1 FROM followers WHERE follower_id=? AND following_id=?').get(req.user.id,id);if(ex){db.prepare('DELETE FROM followers WHERE follower_id=? AND following_id=?').run(req.user.id,id);return res.json({following:false})}db.prepare('INSERT INTO followers(follower_id,following_id,created_at) VALUES(?,?,?)').run(req.user.id,id,now());notify(id,'follow','Nouvel abonné',`${req.dbUser.display_name} vous suit.`,req.user.id,req.user.id);res.json({following:true})});
 app.get('/api/stories',auth,(req,res)=>{db.prepare('DELETE FROM stories WHERE expires_at<=?').run(now());const rows=db.prepare(`SELECT s.*,u.username,u.display_name,u.avatar_url,(SELECT COUNT(*) FROM story_views v WHERE v.story_id=s.id) views,(SELECT 1 FROM story_views v WHERE v.story_id=s.id AND v.user_id=?) viewed FROM stories s JOIN users u ON u.id=s.user_id WHERE s.expires_at>? ORDER BY s.id DESC LIMIT 100`).all(req.user.id,now());res.json({stories:rows})});
 app.post('/api/stories',auth,(req,res)=>{const content=String(req.body?.content||'').trim(),media=String(req.body?.mediaUrl||'').trim()||null;if(!content&&!media)return res.status(400).json({error:'Story vide'});const r=db.prepare('INSERT INTO stories(user_id,media_url,content,created_at,expires_at) VALUES(?,?,?,?,?)').run(req.user.id,media,content,now(),now()+86400000);res.status(201).json({story:db.prepare('SELECT * FROM stories WHERE id=?').get(r.lastInsertRowid)})});
 app.post('/api/stories/:id/view',auth,(req,res)=>{const s=db.prepare('SELECT * FROM stories WHERE id=? AND expires_at>?').get(req.params.id,now());if(!s)return res.status(404).json({error:'Story introuvable'});db.prepare('INSERT OR IGNORE INTO story_views(story_id,user_id,created_at) VALUES(?,?,?)').run(s.id,req.user.id,now());res.json({ok:true})});
 app.post('/api/posts/:id/save',auth,(req,res)=>{const id=Number(req.params.id),ex=db.prepare('SELECT 1 FROM saved_posts WHERE post_id=? AND user_id=?').get(id,req.user.id);if(ex){db.prepare('DELETE FROM saved_posts WHERE post_id=? AND user_id=?').run(id,req.user.id);return res.json({saved:false})}db.prepare('INSERT OR IGNORE INTO saved_posts(post_id,user_id,created_at) VALUES(?,?,?)').run(id,req.user.id,now());res.json({saved:true})});
 app.get('/api/saved',auth,(req,res)=>res.json({posts:db.prepare(`SELECT p.*,u.username,u.display_name,u.avatar_url FROM saved_posts s JOIN posts p ON p.id=s.post_id JOIN users u ON u.id=p.author_id WHERE s.user_id=? ORDER BY s.created_at DESC`).all(req.user.id)}));
 app.post('/api/reports',auth,(req,res)=>{const type=String(req.body?.targetType||''),id=String(req.body?.targetId||''),reason=String(req.body?.reason||'').trim();if(!['post','comment','user','voice'].includes(type)||!id||!reason)return res.status(400).json({error:'Signalement invalide'});const r=db.prepare('INSERT INTO reports(reporter_id,target_type,target_id,reason,created_at) VALUES(?,?,?,?,?)').run(req.user.id,type,id,reason,now());res.status(201).json({id:r.lastInsertRowid})});
 app.get('/api/settings',auth,(req,res)=>res.json({privacy:{privateAccount:false,showOnline:true,allowMessages:true},notifications:{likes:true,comments:true,follows:true,messages:true,voice:true}}));
 console.log('[Moto Voc] Social features loaded');
}
Module._load=function(request,parent,isMain){const loaded=originalLoad.apply(this,arguments);
 if(request==='express'&&typeof loaded==='function'&&!loaded.__motoWrapped){const wrapped=function(){const app=loaded.apply(this,arguments);appRef=app;const originalGet=app.get.bind(app);app.get=function(path,...args){if(path==='*')path='/{*splat}';return originalGet(path,...args)};register();return app};Object.setPrototypeOf(wrapped,loaded);wrapped.__motoWrapped=true;for(const k of Object.keys(loaded))wrapped[k]=loaded[k];return wrapped}
 if(request==='better-sqlite3'&&typeof loaded==='function'&&!loaded.__motoWrapped){const Wrapped=function(...args){const db=new loaded(...args);dbRef=db;register();return db};Wrapped.prototype=loaded.prototype;for(const k of Object.keys(loaded))Wrapped[k]=loaded[k];Wrapped.__motoWrapped=true;return Wrapped}
 return loaded};
